### PR TITLE
fix(bug): build failed with tag "oss"

### PR DESCRIPTION
**Pull request by guessi**
Tried to build with v2.0.2, and quickly found out it's unable to build when tag `oss` is set.

```
cmd/drone-server/inject_store.go:63:19: too many arguments in call to db.Connect

    have (string, string, int)
    want (string, string)
```

introduced by https://github.com/drone/drone/pull/3089

### CODE REVIEW

**Comment by guessi** [comment]
another issue is that `/version` not reflect it's actual version

since the `version/version.go` not updated
https://github.com/drone/drone/blob/v2.0.2/version/version.go#L29-L30

**Comment by eoinmcafee00** [comment]
Thank you @guessi . Merging now.
